# Generated by Django 5.1.4 on 2025-04-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie de produit', 'verbose_name_plural': 'Catégories de produits'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='price_checker.productcategory', verbose_name='Catégorie parente'),
        ),
    ]
