# Generated by Django 5.1.4 on 2025-05-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrée de prix', 'verbose_name_plural': 'Entrées de prix'},
        ),
        migrations.AddField(
            model_name='priceentry',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricevalidation',
            name='price_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='price_checker.priceentry'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
