# Generated by Django 5.1.4 on 2025-04-26 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0002_alter_productcategory_options_productcategory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceentry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
