# Generated by Django 5.1.4 on 2025-04-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0003_priceentry_image_productcategory_image'),
        ('product', '0005_product_created_at_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='product.product'),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='source',
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='price_checker.city'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('APPROVED', 'Approuvé'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Privé'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20, verbose_name='Visibilité')),
                ('target_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix cible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.product')),
            ],
            options={
                'verbose_name': 'Statut du produit',
                'verbose_name_plural': 'Statuts des produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
