# Generated by Django 4.2.10 on 2025-07-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0003_remove_variant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceentry',
            name='proof_image',
            field=models.ImageField(blank=True, help_text="Photo du prix ou de l'étiquette (optionnel)", null=True, upload_to='price_proofs/%Y/%m/%d/', verbose_name='Preuve en image'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='supplier_address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du fournisseur'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fournisseur'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du fournisseur'),
        ),
        migrations.AddField(
            model_name='pricesubmission',
            name='proof_image',
            field=models.ImageField(blank=True, help_text="Photo du prix ou de l'étiquette (optionnel)", null=True, upload_to='price_proofs/%Y/%m/%d/', verbose_name='Preuve en image'),
        ),
        migrations.AddField(
            model_name='pricesubmission',
            name='supplier_address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du fournisseur'),
        ),
        migrations.AddField(
            model_name='pricesubmission',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fournisseur'),
        ),
        migrations.AddField(
            model_name='pricesubmission',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du fournisseur'),
        ),
    ]
