# Generated by Django 5.1.4 on 2025-04-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0004_alter_priceentry_product_and_more'),
        ('price_checker', 'cleanup_orphaned_entries'),
    ]

    operations = [
    ]
