# Generated by Django 5.1.4 on 2025-04-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0005_merge_20250427_0700'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='product.phonevariant'),
        ),
        migrations.AlterUniqueTogether(
            name='priceentry',
            unique_together={('product', 'variant', 'city', 'is_active')},
        ),
    ]
