# Generated by Django 5.1.4 on 2025-04-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0007_priceentry_user'),
        ('product', '0010_alter_phonevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceentry',
            unique_together={('product', 'city', 'is_active')},
        ),
    ]
