# Generated by Django 5.1.4 on 2025-04-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0008_alter_priceentry_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceentry',
            unique_together=set(),
        ),
    ]
