# Generated by Django 5.1.4 on 2025-04-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0009_remove_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_validations', to=settings.AUTH_USER_MODEL)),
                ('price_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='price_checker.priceentry')),
            ],
            options={
                'verbose_name': 'Validation de prix',
                'verbose_name_plural': 'Validations de prix',
                'ordering': ['-created_at'],
            },
        ),
    ]
