# Generated by Django 5.1.4 on 2025-04-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0002_handle_null_users'),
        ('price_checker', '0010_pricevalidation'),
    ]

    operations = [
    ]
