# Generated by Django 5.1.4 on 2025-04-29 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0011_merge_0002_handle_null_users_0010_pricevalidation'),
        ('product', '0010_alter_phonevariant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prix validé', 'verbose_name_plural': 'Prix validés'},
        ),
        migrations.AddField(
            model_name='priceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PriceDeactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_deactivations', to=settings.AUTH_USER_MODEL)),
                ('price_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivations', to='price_checker.priceentry')),
            ],
            options={
                'verbose_name': 'Désactivation de prix',
                'verbose_name_plural': 'Désactivations de prix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to='price_checker.city')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_prices', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to='product.phonevariant')),
            ],
            options={
                'verbose_name': 'Soumission de prix',
                'verbose_name_plural': 'Soumissions de prix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_entry', to='price_checker.pricesubmission'),
        ),
    ]
