"""
Django settings for saga project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import django
from django.core.files.storage import FileSystemStorage
from django.contrib.staticfiles.storage import StaticFilesStorage
from storages.backends.s3boto3 import S3Boto3Storage
import stripe
import dj_database_url
import boto3
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"BASE_DIR: {BASE_DIR}")  # Pour vérifier le chemin

print("\n" + "="*50)
print("Démarrage du chargement des paramètres Django")
print("="*50 + "\n")

# Charger les variables d'environnement
env_path = os.path.join(BASE_DIR, '.env')
print(f"\nRecherche du fichier .env à : {env_path}")

# Vérifier si le fichier existe
if os.path.exists(env_path):
    print("✓ Fichier .env trouvé")
    load_dotenv(env_path)
else:
    print("✗ Fichier .env non trouvé")

# Chemin vers le fichier .env.secrets
env_path = os.path.join(BASE_DIR, 'saga', '.env.secrets')
print(f"\nRecherche du fichier .env.secrets à : {env_path}")

# Vérifier si le fichier existe
if os.path.exists(env_path):
    print("✓ Fichier .env.secrets trouvé")
    load_dotenv(env_path)
else:
    print("✗ Fichier .env.secrets non trouvé")

# ==================================================
# CONFIGURATION DE BASE
# ==================================================
DEBUG = False  # Forcé à False pour tester S3
print(f"\nDEBUG est {'activé' if DEBUG else 'désactivé'}")
print(f"Valeur de DEBUG dans l'environnement : {os.getenv('DEBUG')}")

# Configuration de base
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-for-dev')

# Configuration des hôtes autorisés
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ==================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# ==================================================
DATABASE_URL = os.getenv('DATABASE_URL')

print("\n=== VÉRIFICATION CONFIGURATION BASE DE DONNÉES ===")
if DATABASE_URL and not DEBUG:
    print("Mode : Production (Heroku)")
    print(f"URL de la base de données détectée")
else:
    print("Mode : Développement local")
    print(f"DB_NAME : {os.getenv('DB_NAME')}")
    print(f"DB_USER : {os.getenv('DB_USER')}")
    print(f"DB_HOST : {os.getenv('DB_HOST')}")
    print(f"DB_PORT : {os.getenv('DB_PORT')}")
print("================================================\n")

if DATABASE_URL and not DEBUG:
    # Configuration pour Heroku (Production)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Configuration pour le développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'sslmode': 'disable',
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': True,
        }
    }

# Vérification de la connexion à la base de données
try:
    from django.db import connections
    connections['default'].ensure_connection()
    print("✓ Connexion à la base de données établie avec succès")
    print(f"Base de données utilisée : {DATABASES['default']['NAME']}")
except Exception as e:
    print(f"✗ Erreur de connexion à la base de données : {str(e)}")
    print("\nVeuillez vérifier :")
    print("1. Que PostgreSQL est en cours d'exécution")
    print("2. Que les variables dans .env sont correctes")
    print("3. Que l'utilisateur a les droits nécessaires")

# ==================================================
# CONFIGURATION DES FICHIERS STATIQUES ET MÉDIAS
# ==================================================
# Configuration AWS S3
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')

print("\n=== CONFIGURATION AWS S3 ===")
print(f"AWS_ACCESS_KEY_ID: {'✓ Configuré' if AWS_ACCESS_KEY_ID else '✗ Non configuré'}")
print(f"AWS_SECRET_ACCESS_KEY: {'✓ Configuré' if AWS_SECRET_ACCESS_KEY else '✗ Non configuré'}")
print(f"AWS_STORAGE_BUCKET_NAME: {'✓ Configuré' if AWS_STORAGE_BUCKET_NAME else '✗ Non configuré'}")
print(f"AWS_S3_REGION_NAME: {AWS_S3_REGION_NAME}")
print("===========================\n")

# Vérification des paramètres AWS
if not all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME]):
    raise ValueError("Les variables AWS sont requises. Veuillez configurer AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY et AWS_STORAGE_BUCKET_NAME dans votre fichier .env")

# Configuration S3
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True
AWS_S3_FILE_OVERWRITE = False

# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Dossier static à la racine
]

if not DEBUG:
    STATICFILES_STORAGE = 'saga.storage_backends.StaticStorage'
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"

# Configuration S3 pour les médias (toujours utilisée)
DEFAULT_FILE_STORAGE = 'saga.storage_backends.MediaStorage'
MEDIA_URL = '/media/' if DEBUG else f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Configuration du stockage des fichiers
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Configuration du stockage des fichiers médias
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Configuration des dossiers de stockage
if DEBUG:
    # En développement, utiliser le stockage local
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'
else:
    # En production, utiliser S3
    MEDIA_ROOT = None
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Configuration des dossiers pour les images
PRODUCT_IMAGES_DIR = 'products'  # Dossier racine pour tous les produits
PRODUCT_MAIN_IMAGES_DIR = 'main'  # Sous-dossier pour les images principales
PRODUCT_GALLERY_IMAGES_DIR = 'gallery'  # Sous-dossier pour la galerie

# ==================================================
# CONFIGURATION DE SÉCURITÉ
# ==================================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ==================================================
# CONFIGURATION DES SERVICES EXTERNES
# ==================================================
# Stripe
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
stripe.api_version = '2023-10-16'
stripe.api_key = STRIPE_SECRET_KEY

# Tinify
TINIFY_API_KEY = os.getenv('TINIFY_API_KEY')

# Configuration de l'optimisation d'images
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
MAX_IMAGE_DIMENSIONS = (4000, 4000)
IMAGE_QUALITY = 80

# Formats d'image configurables
IMAGE_FORMATS = {
    'main': {
        'width': 1200,
        'height': 1200,
        'usage': 'product_detail',
        'required': True,
        'description': 'Image principale pour la page détaillée du produit',
        'quality': 85,
        'format': 'JPEG'
    },
    'thumb': {
        'width': 300,
        'height': 300,
        'usage': 'product_list',
        'required': True,
        'description': 'Miniature pour la liste des produits',
        'quality': 80,
        'format': 'JPEG'
    },
    'gallery': {
        'width': 800,
        'height': 800,
        'usage': 'product_gallery',
        'required': True,
        'description': 'Image pour la galerie du produit',
        'quality': 85,
        'format': 'JPEG'
    }
}

# Configuration du cache pour les images
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ==================================================
# CONFIGURATION DE L'EMAIL
# ==================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# ==================================================
# CONFIGURATION REST FRAMEWORK
# ==================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# ==================================================
# LOGGING DE LA CONFIGURATION
# ==================================================
print("\n=== CONFIGURATION DE L'APPLICATION ===")
print(f"Mode : {'Développement' if DEBUG else 'Production'}")
print(f"Base de données : {'Heroku' if DATABASE_URL else 'Locale'}")
print(f"Stockage médias : {'S3' if AWS_STORAGE_BUCKET_NAME else 'Local'}")
print(f"Stripe configuré : {'Oui' if STRIPE_SECRET_KEY else 'Non'}")
print(f"Email configuré : {'Oui' if EMAIL_HOST_USER else 'Non'}")
print("=====================================\n")

# ======================================================================
# PARAMÈTRES DE SÉCURITÉ SSL
# ======================================================================

# Vérifier si nous sommes en production (Heroku)
IS_HEROKU = os.environ.get('HEROKU', '') == 'True'

# Configuration de la redirection HTTPS
if IS_HEROKU:
    # Configuration pour la production (Heroku)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Configuration pour le développement local
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    # Désactiver complètement HSTS en développement
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    # Désactiver la redirection HTTPS
    SECURE_SSL_REDIRECT = False
    # Désactiver les cookies sécurisés
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # Désactiver le proxy SSL
    SECURE_PROXY_SSL_HEADER = None

# Paramètres de cookies sécurisés (communs aux deux environnements)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Protection contre le clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protection contre le sniffing de contenu
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protection XSS
SECURE_BROWSER_XSS_FILTER = True

# Utiliser des en-têtes de sécurité
SECURE_REFERRER_POLICY = 'same-origin'

# Protection contre les attaques de type "Clickjacking"
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Configuration des hôtes autorisés
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = [
        'bolibana-sugu-d56937020d1c.herokuapp.com',
        'bolibana.com',
        'www.bolibana.com'
    ]

# Origines CSRF autorisées
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://bolibana.com',
        'http://www.bolibana.com'
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://bolibana-sugu-d56937020d1c.herokuapp.com',
        'https://bolibana.com',
        'https://www.bolibana.com',
        'http://bolibana.com',
        'http://www.bolibana.com'
    ]

# Configuration CORS
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://bolibana.com',
        'http://www.bolibana.com'
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        'https://bolibana.com',
        'https://www.bolibana.com',
        'https://bolibana-sugu-d56937020d1c.herokuapp.com',
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'product',
    'accounts',
    'suppliers',
    'django_htmx',
    'widget_tweaks',
    'cart.apps.CartConfig',
    'rest_framework',
    'corsheaders', # pour le CORS 
    # 'drf_yasg', # temporairement désactivé pour la collecte des fichiers statiques
    'django_filters', 
    'rest_framework_simplejwt',
    'stripe',
    'crispy_forms',
    'crispy_tailwind',
    'storages',  # Ajout de django-storages
    'cloudinary_storage',
    'cloudinary',
    'tinify',
    'rembg',
    'onnxruntime',
    'price_checker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'saga.settings.FileRequestLoggingMiddleware',  # Ajout du middleware de logging
]

ROOT_URLCONF = 'saga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'saga/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.categories_processor',
                'product.context_processors.categories_processor_high_tech',
                'product.context_processors.category_processor_maison',
                'product.context_processors.categories_processor_quincaillerie',
                'product.context_processors.categrpies_processor_espace_culturel',
                'cart.context_processors.cart_context',
            ],
        },
    },
]
TEMPLATE_CONTEXT_PROCESSORS = [
    'django.template.context_processors.request',

]

WSGI_APPLICATION = 'saga.wsgi.application'


# ======================================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# ======================================================================

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Bamako'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Shopper'
PHONENUMBER_DEFAULT_REGION = "ML"

# Configuration de la redirection après connexion
LOGIN_REDIRECT_URL = 'suppliers:supplier_index'


REVIEW_PRODUCT_MODEL = 'product.Product'

# Configuration du module Django
DJANGO_SETTINGS_MODULE = os.getenv('DJANGO_SETTINGS_MODULE', 'saga.settings')

# Vérification des configurations critiques
print("\n=== CONFIGURATION CRITIQUE ===")
print(f"Mode DEBUG : {'Activé' if DEBUG else 'Désactivé'}")
print(f"Clé secrète configurée : {'Oui' if SECRET_KEY != 'django-insecure-default-key-for-dev' else 'Non'}")
print(f"Clé Stripe configurée : {'Oui' if STRIPE_SECRET_KEY else 'Non'}")
print("=============================\n") 

# Configuration du logging
import logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'file_request': {
            'format': '{asctime} {levelname} {message} - {path} - {method} - {status}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
            'formatter': 'verbose',
        },
        'file_request': {
            'class': 'logging.FileHandler',
            'filename': 'file_requests.log',
            'formatter': 'file_request',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'saga': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'storages': {
            'handlers': ['console', 'file', 'file_request'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file', 'file_request'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'boto3': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'botocore': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Middleware pour logger les requêtes de fichiers
class FileRequestLoggingMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        self.logger = logging.getLogger('storages')

    def __call__(self, request):
        response = self.get_response(request)
        
        # Vérifier si c'est une requête pour un fichier statique ou média
        if request.path.startswith(('/static/', '/media/')):
            self.logger.info(
                f"File request: {request.path}",
                extra={
                    'path': request.path,
                    'method': request.method,
                    'status': response.status_code,
                }
            )
        
        return response 

# Suppression de la configuration WhiteNoise qui entre en conflit avec S3
# if not DEBUG:
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#     MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware') 