"""
Django settings for saga project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import django
from django.core.files.storage import FileSystemStorage
from django.contrib.staticfiles.storage import StaticFilesStorage
from storages.backends.s3boto3 import S3Boto3Storage
import stripe
import dj_database_url
import boto3
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(f"BASE_DIR: {BASE_DIR}")  # Pour vérifier le chemin

print("\n" + "="*50)
print("Démarrage du chargement des paramètres Django")
print("="*50 + "\n")

# Charger les variables d'environnement
env_path = os.path.join(BASE_DIR, '.env')
print(f"\nRecherche du fichier .env à : {env_path}")

# Vrifier si le fichier existe
if os.path.exists(env_path):
    print("[OK] Fichier .env trouv")
    load_dotenv(env_path)
else:
    print("[ERROR] Fichier .env non trouv")

# Chemin vers le fichier .env.secrets
env_path = os.path.join(BASE_DIR, 'saga', '.env.secrets')
print(f"\nRecherche du fichier .env.secrets  : {env_path}")

# Vrifier si le fichier existe
if os.path.exists(env_path):
    print("[OK] Fichier .env.secrets trouv")
    load_dotenv(env_path)
else:
    print("[ERROR] Fichier .env.secrets non trouv")

# ==================================================
# CONFIGURATION DE BASE
# ==================================================
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
print(f"\nDEBUG est {'activé' if DEBUG else 'désactivé'}")
print(f"Valeur de DEBUG dans l'environnement : {os.getenv('DEBUG')}")

# Configuration de base
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-for-dev')

# Configuration des hôtes autorisés
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ==================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# ==================================================
DATABASE_URL = os.getenv('DATABASE_URL')

print("\n=== VÉRIFICATION CONFIGURATION BASE DE DONNÉES ===")
if DATABASE_URL and not DEBUG:
    print("Mode : Production (Heroku)")
    print(f"URL de la base de données détectée")
else:
    print("Mode : Développement local")
    print(f"DB_NAME : {os.getenv('DB_NAME')}")
    print(f"DB_USER : {os.getenv('DB_USER')}")
    print(f"DB_HOST : {os.getenv('DB_HOST')}")
    print(f"DB_PORT : {os.getenv('DB_PORT')}")
print("================================================\n")

if DATABASE_URL and not DEBUG:
    # Configuration pour Heroku (Production)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Configuration pour le développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'sslmode': 'disable',
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': True,
        }
    }

# Vérification de la connexion à la base de données
try:
    from django.db import connections
    connections['default'].ensure_connection()
    print("[OK] Connexion a la base de donnees etablie avec succes")
    print(f"Base de donnees utilisee : {DATABASES['default']['NAME']}")
except Exception as e:
    print(f"[ERROR] Erreur de connexion a la base de donnees : {str(e)}")
    print("\nVeuillez vérifier :")
    print("1. Que PostgreSQL est en cours d'exécution")
    print("2. Que les variables dans .env sont correctes")
    print("3. Que l'utilisateur a les droits nécessaires")

# ==================================================
# CONFIGURATION DES FICHIERS STATIQUES ET MÉDIAS
# ==================================================
# Configuration AWS S3
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-3')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True

# Storage backends
DEFAULT_FILE_STORAGE = 'saga.storage_backends.MediaStorage'
STATICFILES_STORAGE = 'saga.storage_backends.StaticStorage'
PRODUCT_IMAGE_STORAGE = 'saga.storage_backends.ProductImageStorage'
HERO_IMAGE_STORAGE = 'saga.storage_backends.HeroImageStorage'

# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuration du stockage des fichiers statiques
if not DEBUG:
    # En production (Heroku)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False
    WHITENOISE_ALLOW_ALL_ORIGINS = True
    # Configuration S3 pour les médias uniquement
    DEFAULT_FILE_STORAGE = 'saga.storage_backends.MediaStorage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    # En développement (local)
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des dossiers pour les images
PRODUCT_IMAGES_DIR = 'products'  # Dossier racine pour tous les produits
PRODUCT_MAIN_IMAGES_DIR = 'main'  # Sous-dossier pour les images principales
PRODUCT_GALLERY_IMAGES_DIR = 'gallery'  # Sous-dossier pour la galerie

# ==================================================
# CONFIGURATION DE SÉCURITÉ
# ==================================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ==================================================
# CONFIGURATION DE SÉCURITÉ DES PAIEMENTS
# ==================================================
# Limites de sécurité pour les paiements
PAYMENT_RATE_LIMIT = 10  # Requêtes par minute
PAYMENT_MAX_AMOUNT = 1000000  # 1 million FCFA maximum par commande
PAYMENT_SESSION_TIMEOUT = 3600  # 1 heure en secondes

# IPs blacklistées pour les paiements
PAYMENT_BLACKLISTED_IPS = os.getenv('PAYMENT_BLACKLISTED_IPS', '').split(',')

# Configuration de sécurité des sessions de paiement
PAYMENT_SESSION_SECURE = True
PAYMENT_SESSION_HTTPONLY = True

# ==================================================
# CONFIGURATION ORANGE MONEY WEB PAYMENT API
# ==================================================
ORANGE_MONEY_CONFIG = {
    'enabled': os.getenv('ORANGE_MONEY_ENABLED', 'False').lower() == 'true',
    'environment': os.getenv('ORANGE_MONEY_ENV', 'dev'),  # 'dev' ou 'prod'
    'merchant_key': os.getenv('ORANGE_MONEY_MERCHANT_KEY', ''),
    'client_id': os.getenv('ORANGE_MONEY_CLIENT_ID', ''),
    'client_secret': os.getenv('ORANGE_MONEY_CLIENT_SECRET', ''),
    'currency': os.getenv('ORANGE_MONEY_CURRENCY', 'OUV'),  # OUV pour dev, XOF pour prod
    'language': os.getenv('ORANGE_MONEY_LANGUAGE', 'fr'),
    'timeout': int(os.getenv('ORANGE_MONEY_TIMEOUT', '600')),  # 10 minutes par défaut
    'max_retries': int(os.getenv('ORANGE_MONEY_MAX_RETRIES', '3')),
}

# URLs Orange Money selon l'environnement
if ORANGE_MONEY_CONFIG['environment'] == 'prod':
    # Production - URLs corrigées selon la documentation
    ORANGE_MONEY_CONFIG.update({
        'base_url': 'https://api.orange.com',
        'payment_url': 'https://webpayment.orange-money.com',
        'token_url': 'https://api.orange.com/oauth/v3/token',
        'webpayment_url': 'https://api.orange.com/orange-money-webpay/v1/webpayment',
        'status_url': 'https://api.orange.com/orange-money-webpay/v1/transactionstatus',
    })
else:
    # DEV/Sandbox - URLs confirmées par la documentation
    ORANGE_MONEY_CONFIG.update({
        'base_url': 'https://api.orange.com',
        'payment_url': 'https://webpayment-qualif.orange-money.com',
        'token_url': 'https://api.orange.com/oauth/v3/token',
        'webpayment_url': 'https://api.orange.com/orange-money-webpay/dev/v1/webpayment',
        'status_url': 'https://api.orange.com/orange-money-webpay/dev/v1/transactionstatus',
    })

# Configuration des webhooks Orange Money
ORANGE_MONEY_WEBHOOKS = {
    'notification_url': os.getenv('ORANGE_MONEY_NOTIFICATION_URL', ''),
    'return_url': os.getenv('ORANGE_MONEY_RETURN_URL', ''),
    'cancel_url': os.getenv('ORANGE_MONEY_CANCEL_URL', ''),
    'secret_key': os.getenv('ORANGE_MONEY_WEBHOOK_SECRET', ''),
}
PAYMENT_SESSION_SAMESITE = 'Strict'

# Configuration des webhooks Stripe
STRIPE_WEBHOOK_TIMEOUT = 30  # Timeout en secondes
STRIPE_WEBHOOK_MAX_RETRIES = 3

# ==================================================
# CONFIGURATION DE SÉCURITÉ DU PANIER
# ==================================================
# Limites de sécurité pour le panier
CART_MAX_QUANTITY_PER_ITEM = 10  # Quantité maximum par article
CART_MAX_ITEMS = 100  # Nombre maximum d'articles dans le panier
CART_RATE_LIMIT = 100  # Actions par minute sur le panier
CART_SESSION_TIMEOUT = 7200  # 2 heures en secondes

# Protection contre les attaques
CART_CSRF_PROTECTION = True
CART_OWNERSHIP_VERIFICATION = True
CART_STOCK_VALIDATION = True

# ==================================================
# CONFIGURATION ADMIN ET SÉCURITÉ
# ==================================================
# URL d'administration sécurisée
ADMIN_URL = os.getenv('ADMIN_URL', 's3cur3d4dm1n-p4n3l-2024/')

# Configuration des IPs autorisées pour l'admin
ADMIN_ALLOWED_IPS = os.getenv('ADMIN_ALLOWED_IPS', '127.0.0.1').split(',')

# Configuration de la 2FA
OTP_TOTP_ISSUER = 'SagaKore'
OTP_LOGIN_URL = 'accounts:login'
OTP_ADMIN_ENABLED = True
OTP_ENFORCE_ADMIN = True
OTP_ENFORCE_GLOBAL = True
OTP_REQUIRED = True
OTP_ADMIN_REQUIRED = True

# Configuration des URLs de login
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'suppliers:supplier_index'
LOGOUT_REDIRECT_URL = 'suppliers:supplier_index'
OTP_REDIRECT_URL = 'suppliers:supplier_index'

# ==================================================
# CONFIGURATION DES SERVICES EXTERNES
# ==================================================
# Stripe
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
stripe.api_version = '2023-10-16'
stripe.api_key = STRIPE_SECRET_KEY

# Tinify
TINIFY_API_KEY = os.getenv('TINIFY_API_KEY')



# Configuration de l'optimisation d'images
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
MAX_IMAGE_DIMENSIONS = (4000, 4000)
IMAGE_QUALITY = 80

# Formats d'image configurables
IMAGE_FORMATS = {
    'main': {
        'width': 1200,
        'height': 1200,
        'usage': 'product_detail',
        'required': True,
        'description': 'Image principale pour la page détaillée du produit',
        'quality': 85,
        'format': 'JPEG'
    },
    'thumb': {
        'width': 300,
        'height': 300,
        'usage': 'product_list',
        'required': True,
        'description': 'Miniature pour la liste des produits',
        'quality': 80,
        'format': 'JPEG'
    },
    'gallery': {
        'width': 800,
        'height': 800,
        'usage': 'product_gallery',
        'required': True,
        'description': 'Image pour la galerie du produit',
        'quality': 85,
        'format': 'JPEG'
    }
}

# Configuration du cache pour les images
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ==================================================
# CONFIGURATION DE L'EMAIL
# ==================================================
if DEBUG:
    # Configuration pour le dveloppement avec envoi d'emails reels
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'dev@localhost')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    print("[INFO] Email configure en mode SMTP (developpement)")
    
    # Fallback vers console si pas de configuration SMTP ou si erreur d'authentification
    if not EMAIL_HOST_PASSWORD:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        print("[WARN] Pas de mot de passe SMTP configure - emails en mode console")
    else:
        # Test de connexion SMTP
        try:
            import smtplib
            server = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
            server.starttls()
            server.login(EMAIL_HOST_USER, EMAIL_HOST_PASSWORD)
            server.quit()
            print("[OK] Connexion SMTP testee avec succes")
        except Exception as e:
            print(f"[WARN] Erreur de connexion SMTP: {str(e)}")
            print("[INFO] Basculement vers le mode console")
            EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En production, utiliser SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    print("[INFO] Email configure en mode SMTP (production)")

# Email par dfaut
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
print(f"[INFO] Email configure : {'Oui' if EMAIL_HOST_USER else 'Non'}")

# ==================================================
# CONFIGURATION DE L'APP DE GESTION DE STOCK (B2B)
# ==================================================
# URL de base de l'API B2B
B2B_API_URL = os.getenv('B2B_API_URL', 'https://www.bolibanastock.com/api/v1')

# Token API pour authentifier les requêtes vers l'app de gestion de stock
# Ce token est créé et géré dans le projet B2B (BoliBanaStock)
# Il doit être stocké dans le fichier .env (NE PAS COMMITER)
B2B_API_KEY = os.getenv('B2B_API_KEY', '')
if not B2B_API_KEY:
    print("[WARN] B2B_API_KEY n'est pas configuré dans .env")

# Configuration pour les appels API vers l'app de gestion de stock
INVENTORY_API_TIMEOUT = int(os.getenv('INVENTORY_API_TIMEOUT', '30'))  # Timeout en secondes
INVENTORY_API_MAX_RETRIES = int(os.getenv('INVENTORY_API_MAX_RETRIES', '3'))
INVENTORY_SYNC_FREQUENCY = int(os.getenv('INVENTORY_SYNC_FREQUENCY', '60'))  # Fréquence par défaut en minutes

# Clé de chiffrement pour les clés API stockées en base de données
# Générer avec: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
def _normalize_fernet_key(raw_value: str) -> str:
    """
    Normalise une clé Fernet lue depuis l'environnement.
    - supprime espaces/newlines
    - enlève les guillemets simples/doubles éventuels
    - enlève un éventuel préfixe b'...' copié depuis Python
    """
    value = (raw_value or '').strip()
    if (value.startswith("b'") and value.endswith("'")) or (value.startswith('b"') and value.endswith('"')):
        value = value[2:-1]
    if (value.startswith("'") and value.endswith("'")) or (value.startswith('"') and value.endswith('"')):
        value = value[1:-1]
    return value.strip()

INVENTORY_ENCRYPTION_KEY = _normalize_fernet_key(os.getenv('INVENTORY_ENCRYPTION_KEY', ''))
if not INVENTORY_ENCRYPTION_KEY:
    print("[WARN] INVENTORY_ENCRYPTION_KEY n'est pas configuré dans .env - les clés API seront chiffrées avec une clé temporaire")
else:
    # Validation "soft" (ne pas planter le démarrage, mais logguer clairement)
    try:
        from cryptography.fernet import Fernet
        Fernet(INVENTORY_ENCRYPTION_KEY.encode())
    except Exception as e:
        # Ne jamais afficher la clé en clair dans les logs
        print(f"[ERROR] INVENTORY_ENCRYPTION_KEY invalide (Fernet): {e}")

# Logs de diagnostic (sans fuite de secrets)
if B2B_API_KEY:
    print(f"[INFO] B2B_API_KEY présent: len={len(B2B_API_KEY)}")
else:
    print("[WARN] B2B_API_KEY absent")
if INVENTORY_ENCRYPTION_KEY:
    print(f"[INFO] INVENTORY_ENCRYPTION_KEY présent: len={len(INVENTORY_ENCRYPTION_KEY)}")

# ==================================================
# CONFIGURATION REST FRAMEWORK
# ==================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Configuration JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==================================================
# LOGGING DE LA CONFIGURATION
# ==================================================
print("\n=== CONFIGURATION DE L'APPLICATION ===")
print(f"Mode : {'Développement' if DEBUG else 'Production'}")
print(f"Base de données : {'Heroku' if DATABASE_URL else 'Locale'}")
print(f"Stockage médias : {'S3' if AWS_STORAGE_BUCKET_NAME else 'Local'}")
print(f"Stripe configuré : {'Oui' if STRIPE_SECRET_KEY else 'Non'}")
print(f"Email configuré : {'Oui' if EMAIL_HOST_USER else 'Non'}")
print("=====================================\n")

# ======================================================================
# PARAMÈTRES DE SÉCURITÉ SSL
# ======================================================================

# Vérifier si nous sommes en production (Heroku)
IS_HEROKU = os.environ.get('HEROKU', '') == 'True'

# Configuration de la redirection HTTPS
if IS_HEROKU:
    # Configuration pour la production (Heroku)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Configuration pour le développement local
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    # Désactiver complètement HSTS en développement
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    # Désactiver la redirection HTTPS
    SECURE_SSL_REDIRECT = False
    # Désactiver les cookies sécurisés
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # Désactiver le proxy SSL
    SECURE_PROXY_SSL_HEADER = None

# Paramètres de cookies sécurisés (communs aux deux environnements)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Protection contre le clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protection contre le sniffing de contenu
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protection XSS
SECURE_BROWSER_XSS_FILTER = True

# Utiliser des en-têtes de sécurité
SECURE_REFERRER_POLICY = 'same-origin'

# Protection contre les attaques de type "Clickjacking"
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Configuration des hôtes autorisés
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.7', '0.0.0.0']
else:
    ALLOWED_HOSTS = [
        'bolibana-sugu-d56937020d1c.herokuapp.com',
        'bolibana.com',
        'www.bolibana.com'
    ]

# Origines CSRF autorisées
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://192.168.1.7:8000',
        'http://bolibana.com',
        'http://www.bolibana.com'
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://bolibana-sugu-d56937020d1c.herokuapp.com',
        'https://bolibana.com',
        'https://www.bolibana.com',
        'http://bolibana.com',
        'http://www.bolibana.com'
    ]

# Configuration CORS
if DEBUG:
    # Autoriser toutes les origines en développement pour l'app mobile
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://bolibana.com',
        'http://www.bolibana.com',
    ]
    # Autoriser les credentials pour l'authentification
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOWED_ORIGINS = [
        'https://bolibana.com',
        'https://www.bolibana.com',
        'https://bolibana-sugu-d56937020d1c.herokuapp.com',
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    # 'saga',  # Temporairement désactivé pour les tests
    'product',
    'accounts.apps.AccountsConfig',
    'suppliers',
    'core.apps.CoreConfig',
    'django_htmx',
    'widget_tweaks',
    'cart.apps.CartConfig',
    'rest_framework',
    'corsheaders',
    'django_filters', 
    'rest_framework_simplejwt',
    'stripe',
    'crispy_forms',
    'crispy_tailwind',
    'storages',
    'cloudinary_storage',
    'cloudinary',
    'tinify',
    'rembg',
    'onnxruntime',
    'price_checker',
    'inventory.apps.InventoryConfig',  # App de gestion de stock
    # Applications pour la 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'axes',
    'simple_history',
]

# Configuration Crispy Forms
CRISPY_TEMPLATE_PACK = 'tailwind'
CRISPY_ALLOWED_TEMPLATE_PACKS = ('tailwind',)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'saga.middleware.SecurityMiddleware',  # Middleware de sécurité personnalisé
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.CookieConsentMiddleware',  # Middleware pour le consentement cookies
    'core.middleware.AnalyticsMiddleware',  # Middleware pour le tracking automatique
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Middleware Axes pour la protection brute-force
    'core.middleware.MaintenanceModeMiddleware',  # Après AuthenticationMiddleware pour accéder à request.user
    'django_otp.middleware.OTPMiddleware',  # Middleware OTP juste après AuthenticationMiddleware
    'saga.middleware.AdminIPRestrictionMiddleware',  # Middleware de restriction IP
    'inventory.middleware.AutoSyncB2BMiddleware',  # Synchronisation automatique des produits B2B
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'saga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'saga/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.dropdown_categories_processor',
                'cart.context_processors.cart_context',
                'suppliers.context_processors.user_context',
                'core.context_processors.site_config',
                'inventory.context_processors.synced_categories_context',
            ],
        },
    },
]
TEMPLATE_CONTEXT_PROCESSORS = [
    'django.template.context_processors.request',

]

WSGI_APPLICATION = 'saga.wsgi.application'


# ======================================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# ======================================================================

# Configuration des validateurs de mot de passe
AUTH_PASSWORD_VALIDATORS = [
# ... existing code ...
]

# Configuration d'Axes (Protection Brute-Force)
AXES_FAILURE_LIMIT = 5  # Nombre de tentatives avant blocage
AXES_COOLOFF_TIME = 1   # Temps de blocage en heures
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # Bloquer par couple Utilisateur + IP
AXES_RESET_ON_SUCCESS = True  # Réinitialiser le compteur en cas de succès
AXES_LOCKOUT_TEMPLATE = 'accounts/lockout.html'  # Template personnalisé pour le blocage

# Configuration de l'authentification
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Backend Axes pour le suivi des tentatives
    'django.contrib.auth.backends.ModelBackend',  # Backend par défaut
]

# Internationalization
# ... existing code ...

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Bamako'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Shopper'
PHONENUMBER_DEFAULT_REGION = "ML"

# Configuration du module Django
DJANGO_SETTINGS_MODULE = os.getenv('DJANGO_SETTINGS_MODULE', 'saga.settings')

# Vérification des configurations critiques
print("\n=== CONFIGURATION CRITIQUE ===")
print(f"Mode DEBUG : {'Activé' if DEBUG else 'Désactivé'}")
print(f"Clé secrète configurée : {'Oui' if SECRET_KEY != 'django-insecure-default-key-for-dev' else 'Non'}")
print(f"Clé Stripe configurée : {'Oui' if STRIPE_SECRET_KEY else 'Non'}")
print("=============================\n") 

# Configuration du logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'heroku_verbose': {
            'format': '{asctime} - {name} - {levelname} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}',
            'style': '%',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'security.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'heroku_console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'heroku_verbose': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'heroku_verbose',
        },
        'security_alert': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'heroku_console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console', 'heroku_console'],
            'level': 'INFO',
            'propagate': True,
        },
        'saga.cart': {
            'handlers': ['file', 'console', 'heroku_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'cart.checkout': {
            'handlers': ['heroku_verbose'],
            'level': 'INFO',
            'propagate': False,
        },
        'inventory': {
            'handlers': ['file', 'console', 'heroku_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console', 'heroku_console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'admin_access': {
            'handlers': ['security_file', 'console', 'heroku_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'payment_security': {
            'handlers': ['security_file', 'console', 'heroku_console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'rate_limit': {
            'handlers': ['security_file', 'console', 'heroku_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'suspicious_activity': {
            'handlers': ['security_file', 'console', 'heroku_console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Suppression de la configuration WhiteNoise qui entre en conflit avec S3
# if not DEBUG:
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#     MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware') 

# Configuration des templates d'erreur personnalisés
if not DEBUG:
    # Templates d'erreur personnalisés pour la production
    TEMPLATES[0]['DIRS'].append(BASE_DIR / 'saga' / 'templates')
    
    # Configuration des gestionnaires d'erreur
    HANDLER404 = 'core.views.custom_404'
    HANDLER500 = 'core.views.custom_500'
    HANDLER403 = 'core.views.custom_403'

REVIEW_PRODUCT_MODEL = 'product.Product' 

if not DEBUG:
    HANDLER404 = 'core.views.custom_404'
    HANDLER500 = 'core.views.custom_500'
    HANDLER403 = 'core.views.custom_403'
