"""
Django settings for saga project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import logging
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Retour à la configuration d'origine
print(f"BASE_DIR: {BASE_DIR}")  # Pour vérifier le chemin
import stripe
import dj_database_url

# Configuration des logs
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('django.log')
    ]
)
logger = logging.getLogger(__name__)

print("\n" + "="*50)
print("Démarrage du chargement des paramètres Django")
print("="*50 + "\n")

# Charger les variables d'environnement
env_path = os.path.join(BASE_DIR, 'saga/.env.secrets')  # Chemin corrigé
print(f"Chemin du fichier .env.secrets: {env_path}")  # Pour vérifier le chemin
load_dotenv(env_path)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
print(f"SECRET_KEY chargée: {'Oui' if SECRET_KEY else 'Non'}")

# Les autres configurations Stripe sont déjà chargées
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
print("STRIPE_PUBLIC_KEY:", STRIPE_PUBLIC_KEY)
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
print("STRIPE_SECRET_KEY:", STRIPE_SECRET_KEY)
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
print("STRIPE_WEBHOOK_SECRET:", STRIPE_WEBHOOK_SECRET)
STRIPE_API_VERSION = os.getenv('STRIPE_API_VERSION')
print("STRIPE_API_VERSION:", STRIPE_API_VERSION)
print(f"Configuration Stripe chargée: {'Oui' if STRIPE_SECRET_KEY else 'Non'}")

# Configuration Stripe
stripe.api_version = '2023-10-16'  # Utiliser la dernière version stable
stripe.api_key = STRIPE_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Configuration de sécurité SSL
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0  # Désactivé
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_PROXY_SSL_HEADER = None
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Configuration des cookies
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None

# Domaines autorisés
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.herokuapp.com',
    'bolibana-sugu-d56937020d1c.herokuapp.com',
    'bolibana.com',
    'www.bolibana.com',
]

# Origines CSRF autorisées
CSRF_TRUSTED_ORIGINS = [
    'https://bolibana-sugu-d56937020d1c.herokuapp.com',
    'https://bolibana.com',
    'https://www.bolibana.com',
]

# Configuration CORS
CORS_ALLOWED_ORIGINS = [
    'https://bolibana.com',
    'https://www.bolibana.com',
    'https://bolibana-sugu-d56937020d1c.herokuapp.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'product',
    'accounts',
    'suppliers',
    'django_htmx',
    'widget_tweaks',
    'cart.apps.CartConfig',
    'rest_framework',
    'corsheaders', # pour le CORS 
    # 'drf_yasg', # temporairement désactivé pour la collecte des fichiers statiques
    'django_filters', 
    'rest_framework_simplejwt',
    'stripe',
    'crispy_forms',
    'crispy_tailwind',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'saga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'saga/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.categories_processor',
                'product.context_processors.categories_processor_high_tech',
                'product.context_processors.category_processor_maison',
                'product.context_processors.categories_processor_quincaillerie',
                'product.context_processors.categrpies_processor_espace_culturel',
                'cart.context_processors.cart_context',
            ],
        },
    },
]
TEMPLATE_CONTEXT_PROCESSORS = [
    'django.template.context_processors.request',

]

WSGI_APPLICATION = 'saga.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('HEROKU_POSTGRESQL_AQUA_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600,
        ssl_require=True
    )
}

# Configuration de la base de données pour le développement local
if DEBUG and not os.getenv('HEROKU'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'saga/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'saga/staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'saga/static'),
    # other static file directories...
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Shopper'
PHONENUMBER_DEFAULT_REGION = "ML"

# Configuration de la redirection après connexion
LOGIN_REDIRECT_URL = 'supplier_index'


REVIEW_PRODUCT_MODEL = 'product.Product'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pymalien@gmail.com'
EMAIL_HOST_PASSWORD = """oild dqvk cabx jbcj"""

# Paramètres REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Paramètres JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Configuration de crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Configuration de WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuration supplémentaire pour WhiteNoise
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True 