# Generated by Django 4.2.10 on 2026-01-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_apikey_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryconnection',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='salesync',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesync',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='salesync',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='stocksite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stocksite',
            name='connection',
        ),
        migrations.AlterModelOptions(
            name='externalcategory',
            options={'verbose_name': 'Catégorie externe (B2B)', 'verbose_name_plural': 'Catégories externes (B2B)'},
        ),
        migrations.AlterModelOptions(
            name='externalproduct',
            options={'verbose_name': 'Produit externe (B2B)', 'verbose_name_plural': 'Produits externes (B2B)'},
        ),
        migrations.RemoveIndex(
            model_name='apikey',
            name='inventory_a_connect_idx',
        ),
        migrations.RemoveIndex(
            model_name='externalcategory',
            name='inventory_externalcategory_external_idx',
        ),
        migrations.RemoveIndex(
            model_name='externalproduct',
            name='inventory_externalproduct_external_idx',
        ),
        migrations.RenameIndex(
            model_name='externalproduct',
            new_name='inventory_e_sync_st_ece659_idx',
            old_name='inventory_externalproduct_sync_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='externalcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='externalproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='connection',
        ),
        migrations.AlterField(
            model_name='externalcategory',
            name='external_id',
            field=models.IntegerField(verbose_name='ID externe (B2B)'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='external_id',
            field=models.IntegerField(verbose_name='ID externe (B2B)'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcategory',
            unique_together={('external_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='externalproduct',
            unique_together={('external_id',)},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='inventory_a_is_acti_ced925_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcategory',
            index=models.Index(fields=['external_id'], name='inventory_e_externa_9af9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['external_id'], name='inventory_e_externa_8079a1_idx'),
        ),
        migrations.DeleteModel(
            name='SaleSync',
        ),
        migrations.DeleteModel(
            name='StockSite',
        ),
        migrations.RemoveField(
            model_name='externalcategory',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='externalproduct',
            name='connection',
        ),
        migrations.DeleteModel(
            name='InventoryConnection',
        ),
    ]
