# Generated by Django 4.2.10 on 2026-01-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryconnection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproduct',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text="Cocher si ce produit est destiné au B2B (sinon c'est un produit B2C)", verbose_name='Produit B2B'),
        ),
    ]
