# Generated by Django 5.0.2 on 2025-04-20 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('highlight', models.TextField(blank=True, null=True, verbose_name='Points forts')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_delivery_days', models.PositiveSmallIntegerField()),
                ('max_delivery_days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_product', serialize=False, to='product.product')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('image', models.ImageField(blank=True, upload_to='product/galerie/')),
                ('ordre', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_products', to='product.product')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('operating_system', models.CharField(max_length=50, verbose_name="Système d'exploitation")),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Taille d'écran (pouces)")),
                ('resolution', models.CharField(max_length=50, verbose_name='Résolution')),
                ('processor', models.CharField(max_length=100, verbose_name='Processeur')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM (Go)')),
                ('battery_capacity', models.PositiveIntegerField(verbose_name='Capacité batterie (mAh)')),
                ('camera_main', models.CharField(max_length=100, verbose_name='Appareil photo principal')),
                ('camera_front', models.CharField(max_length=100, verbose_name='Appareil photo frontal')),
                ('network', models.CharField(max_length=100, verbose_name='Réseaux supportés')),
                ('warranty', models.CharField(max_length=100, verbose_name='Garantie')),
                ('imei', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IMEI')),
                ('is_new', models.BooleanField(default=True, verbose_name='Neuf')),
                ('box_included', models.BooleanField(default=True, verbose_name='Boîte incluse')),
                ('accessories', models.TextField(blank=True, null=True, verbose_name='Accessoires inclus')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='product.product', verbose_name='Produit associé')),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.PositiveIntegerField(verbose_name='Stockage (Go)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Couleur')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.phone', verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Variante de téléphone',
                'verbose_name_plural': 'Variantes de téléphone',
                'unique_together': {('phone', 'color', 'storage')},
            },
        ),
        migrations.CreateModel(
            name='PhoneVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone_variants/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.phonevariant')),
            ],
            options={
                'verbose_name': 'Image de variante',
                'verbose_name_plural': 'Images de variantes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clothing_product', serialize=False, to='product.product')),
                ('gender', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('color', models.ManyToManyField(blank=True, null=True, related_name='clothing_color', to='product.color')),
                ('size', models.ManyToManyField(blank=True, null=True, related_name='clothing_size', to='product.size')),
            ],
        ),
    ]
