# Generated by Django 5.1.4 on 2025-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='image_urls',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='URLs des images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='URLs des images'),
        ),
    ]
