# Generated by Django 5.2a1 on 2025-01-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
