# Generated by Django 5.1.4 on 2025-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='clothing_color', to='product.color'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='clothing_size', to='product.size'),
        ),
    ]
