# Generated by Django 5.1.4 on 2025-05-15 06:36

import django.db.models.deletion
import django.utils.timezone
import product.models
import saga.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_imageproduct_image_urls_product_image_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'ordering': ['ordre', 'created_at'], 'verbose_name': 'Image produit', 'verbose_name_plural': 'Images produit'},
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='is_main',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to=product.models.get_product_gallery_image_upload_path),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to=product.models.get_product_main_image_upload_path),
        ),
    ]
