# Generated by Django 5.0.2 on 2025-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_fix_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='storage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stockage (Go)'),
        ),
    ]
