# Generated by Django 5.2a1 on 2025-01-29 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_clothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clothing_product', serialize=False, to='product.product')),
                ('gender', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('color', models.ManyToManyField(blank=True, null=True, related_name='clothing_color', to='product.color')),
                ('size', models.ManyToManyField(blank=True, null=True, related_name='clothing_size', to='product.size')),
            ],
        ),
    ]
