# Generated by Django 5.1.4 on 2025-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_clothing_color_alter_clothing_size'),
        ('product', '0002_import_products'),
    ]

    operations = [
    ]
