# Generated by Django 5.2a1 on 2025-04-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_generate_slugs'),
        ('product', '0003_category_slug'),
    ]

    operations = [
    ]
