# Generated by Django 5.1.4 on 2025-05-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_imageproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'verbose_name': 'Méthode de livraison', 'verbose_name_plural': 'Méthodes de livraison'},
        ),
    ]
