# Generated by Django 5.1.4 on 2025-05-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_add_network_field'),
        ('product', '0003_add_camera_fields'),
    ]

    operations = [
    ]
