# Generated by Django 5.2a1 on 2025-01-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_culturalitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CulturalItem',
        ),
    ]
