# Generated by Django 5.2a1 on 2025-04-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_0002_generate_slugs_0003_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone_product', serialize=False, to='product.product')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('operating_system', models.CharField(max_length=50, verbose_name="Système d'exploitation")),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Taille d'écran (pouces)")),
                ('resolution', models.CharField(max_length=50, verbose_name='Résolution')),
                ('processor', models.CharField(max_length=100, verbose_name='Processeur')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM (Go)')),
                ('storage', models.PositiveIntegerField(verbose_name='Stockage (Go)')),
                ('battery_capacity', models.PositiveIntegerField(verbose_name='Capacité batterie (mAh)')),
                ('camera_main', models.CharField(max_length=100, verbose_name='Appareil photo principal')),
                ('camera_front', models.CharField(max_length=100, verbose_name='Appareil photo frontal')),
                ('network', models.CharField(max_length=100, verbose_name='Réseaux supportés')),
                ('warranty', models.CharField(max_length=100, verbose_name='Garantie')),
                ('imei', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IMEI')),
                ('is_new', models.BooleanField(default=True, verbose_name='Neuf')),
                ('box_included', models.BooleanField(default=True, verbose_name='Boîte incluse')),
                ('accessories', models.TextField(blank=True, null=True, verbose_name='Accessoires inclus')),
                ('color', models.ManyToManyField(related_name='phone_colors', to='product.color', verbose_name='Couleurs disponibles')),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
