# Generated by Django 5.1.4 on 2025-05-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_load_initial_data'),
    ]

    operations = [
    ]
