# Generated by Django 5.1.4 on 2025-04-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_created_at_product_is_active_and_more'),
        ('product', 'add_product_fields'),
    ]

    operations = [
    ]
