# Generated by Django 5.1.4 on 2025-05-18 14:04

import product.models
import saga.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_unique_together_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to=product.models.get_product_main_image_upload_path, verbose_name='Image principale'),
        ),
    ]
