# Generated by Django 5.2a1 on 2025-04-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_phone_id_alter_phone_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['model'], 'verbose_name': 'Téléphone', 'verbose_name_plural': 'Téléphones'},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='brand',
        ),
    ]
