# Generated by Django 5.2a1 on 2025-01-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_culturalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalitem',
            name='id',
        ),
        migrations.AddField(
            model_name='culturalitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_product', serialize=False, to='product.product'),
        ),
    ]
