# Generated by Django 5.1.4 on 2025-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models

def check_and_remove_id_columns(apps, schema_editor):
    # Vérifier si les colonnes existent avant de les supprimer
    db = schema_editor.connection.cursor()
    
    # Vérifier la colonne id dans product_clothing
    db.execute("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'product_clothing' 
        AND column_name = 'id'
    """)
    if db.fetchone():
        db.execute("ALTER TABLE product_clothing DROP COLUMN id")
    
    # Vérifier la colonne id dans product_culturalitem
    db.execute("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'product_culturalitem' 
        AND column_name = 'id'
    """)
    if db.fetchone():
        db.execute("ALTER TABLE product_culturalitem DROP COLUMN id")

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20250506_1657'),
    ]

    operations = [
        migrations.RunPython(check_and_remove_id_columns),
        migrations.AlterField(
            model_name='clothing',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clothing_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='culturalitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_product', to='product.product'),
        ),
    ]
