# Generated by Django 5.1.4 on 2025-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models

def remove_primary_keys(apps, schema_editor):
    # Supprimer les contraintes de clé primaire existantes avec CASCADE
    schema_editor.execute("""
        ALTER TABLE product_clothing DROP CONSTRAINT IF EXISTS product_clothing_pkey CASCADE;
        ALTER TABLE product_culturalitem DROP CONSTRAINT IF EXISTS product_culturalitem_pkey CASCADE;
    """)
    
    # Supprimer les colonnes id
    schema_editor.execute("""
        ALTER TABLE product_clothing DROP COLUMN IF EXISTS id;
        ALTER TABLE product_culturalitem DROP COLUMN IF EXISTS id;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_load_initial_data'),
    ]

    operations = [
        migrations.RunPython(remove_primary_keys),
        migrations.AlterField(
            model_name='clothing',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clothing_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='culturalitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_product', to='product.product'),
        ),
    ]
