# Generated by Django 5.1.4 on 2025-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_salam',
            field=models.BooleanField(default=False, verbose_name='Produit Salam'),
        ),
    ]
