# Generated by Django 5.1.4 on 2025-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models

def remove_id_columns(apps, schema_editor):
    # Supprimer la colonne id de product_clothing
    schema_editor.execute("""
        ALTER TABLE product_clothing DROP COLUMN IF EXISTS id;
    """)
    
    # Supprimer la colonne id de product_culturalitem
    schema_editor.execute("""
        ALTER TABLE product_culturalitem DROP COLUMN IF EXISTS id;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20250506_1657'),
    ]

    operations = [
        migrations.RunPython(remove_id_columns),
        migrations.AlterField(
            model_name='clothing',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clothing_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='culturalitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cultural_product', to='product.product'),
        ),
    ]
