# Generated by Django 5.1.4 on 2025-05-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_clothing_id_remove_culturalitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='culturalitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_product', to='product.product'),
        ),
    ]
