# Generated by Django 5.1.4 on 2025-04-27 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_created_at'),
        ('suppliers', '0002_alter_supplier_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonevariant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Variante de téléphone', 'verbose_name_plural': 'Variantes de téléphones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterUniqueTogether(
            name='phonevariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='storage',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'category')},
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='ram',
            field=models.PositiveIntegerField(default=16, verbose_name='RAM (GB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_variants', to='product.color'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.phone'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='storage',
            field=models.PositiveIntegerField(verbose_name='Stockage (GB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='phonevariant',
            unique_together={('phone', 'color', 'storage', 'ram')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
