# Generated by Django 5.1.4 on 2025-05-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_salam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'Vêtement', 'verbose_name_plural': 'Vêtements'},
        ),
        migrations.AddField(
            model_name='clothing',
            name='care_instructions',
            field=models.TextField(blank=True, help_text="Instructions d'entretien", null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='fabric_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='fabric_type',
            field=models.CharField(blank=True, choices=[('BAZIN', 'Bazin'), ('WAX', 'Wax'), ('KENTE', 'Kente'), ('BOGOLAN', 'Bogolan'), ('OTHER', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur en mètres', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='origin',
            field=models.CharField(blank=True, help_text="Pays d'origine du tissu", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='pattern',
            field=models.CharField(blank=True, help_text='Motif ou design du tissu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='type',
            field=models.CharField(choices=[('CLOTHING', 'Vêtement'), ('FABRIC', 'Tissu')], default='CLOTHING', max_length=20),
        ),
        migrations.AddField(
            model_name='clothing',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en mètres', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('U', 'Unisexe')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(choices=[('BAZIN', 'Bazin'), ('WAX', 'Wax'), ('KENTE', 'Kente'), ('BOGOLAN', 'Bogolan'), ('OTHER', 'Autre')], default='BAZIN', max_length=20)),
                ('quality', models.CharField(default='Super Riche', max_length=100)),
                ('length', models.DecimalField(decimal_places=2, default=3.0, help_text='Longueur en mètres', max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, default=1.5, help_text='Largeur en mètres', max_digits=4)),
                ('pattern', models.CharField(blank=True, help_text='Motif ou design du tissu', max_length=100, null=True)),
                ('origin', models.CharField(blank=True, help_text="Pays d'origine du tissu", max_length=100, null=True)),
                ('care_instructions', models.TextField(blank=True, help_text="Instructions d'entretien", null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Tissu',
                'verbose_name_plural': 'Tissus',
            },
        ),
    ]
