# Generated by Django 5.2a1 on 2025-04-14 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_phone_options_remove_phone_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='color',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='storage',
        ),
        migrations.CreateModel(
            name='PhoneVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.PositiveIntegerField(verbose_name='Stockage (Go)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Couleur')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.phone', verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Variante de téléphone',
                'verbose_name_plural': 'Variantes de téléphone',
                'unique_together': {('phone', 'color', 'storage')},
            },
        ),
    ]
