# Generated by Django 5.2a1 on 2025-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_culturalitem_id_culturalitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='highlight',
        ),
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
