# Generated by Django 5.1.4 on 2025-05-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_clothing_id_remove_culturalitem_id_and_more'),
    ]

    operations = [
    ]
