# Generated by Django 5.1.4 on 2025-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_phonevariant_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Téléphone', 'verbose_name_plural': 'Téléphones'},
        ),
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='Tecno', max_length=50, verbose_name='Marque'),
        ),
    ]
