# Generated by Django 5.2a1 on 2025-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_phone_color_remove_phone_storage_phonevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonevariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phone_variants/', verbose_name='Image de la variante'),
        ),
    ]
