# Generated by Django 5.2a1 on 2025-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_clothing_detail_remove_clothing_highlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_delivery_days', models.PositiveSmallIntegerField()),
                ('max_delivery_days', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
