# Generated by Django 5.1.4 on 2025-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_clothing_options_clothing_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='bazin_quality',
            field=models.CharField(blank=True, choices=[('SUPER_RICHE', 'Super Riche'), ('RICHE', 'Riche'), ('MOYEN', 'Moyen'), ('BASIQUE', 'Basique')], max_length=20, null=True),
        ),
    ]
