# Generated by Django 5.1.4 on 2025-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_phone_options_phone_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonevariant',
            options={'ordering': ['phone', 'storage', 'ram', 'color'], 'verbose_name': 'Variante de téléphone', 'verbose_name_plural': 'Variantes de téléphones'},
        ),
        migrations.AddField(
            model_name='phonevariant',
            name='disponible_salam',
            field=models.BooleanField(default=False, verbose_name='Disponible en Salam'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='ram',
            field=models.PositiveIntegerField(verbose_name='RAM (Go)'),
        ),
        migrations.AlterField(
            model_name='phonevariant',
            name='storage',
            field=models.PositiveIntegerField(verbose_name='Stockage (Go)'),
        ),
    ]
