# Generated by Django 5.2a1 on 2025-02-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_shippingmethod'),
        ('suppliers', '0002_remove_supplier_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier'),
        ),
    ]
