# Generated by Django 5.1.4 on 2025-05-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_clothing_bazin_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Identifiant unique du tissu', max_length=50, unique=True),
        ),
    ]
