# Generated by Django 5.2a1 on 2025-04-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_phonevariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonevariant',
            name='image',
        ),
        migrations.CreateModel(
            name='PhoneVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone_variants/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.phonevariant')),
            ],
            options={
                'verbose_name': 'Image de variante',
                'verbose_name_plural': 'Images de variantes',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
