# Generated by Django 5.1.4 on 2025-05-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0010_fabric_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('MODEL', 'Catégorie liée à un modèle'), ('FILTER', 'Catégorie avec filtres'), ('MARKETING', 'Catégorie marketing')], default='MODEL', help_text='Type de catégorie', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('blue', 'Bleu'), ('purple', 'Violet'), ('yellow', 'Jaune'), ('red', 'Rouge'), ('green', 'Vert'), ('indigo', 'Indigo'), ('pink', 'Rose')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Modèle lié à cette catégorie', limit_choices_to={'app_label__in': ['product', 'suppliers'], 'model__in': ['phone', 'clothing', 'fabric', 'culturalitem', 'product']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Critères de filtrage pour les sous-catégories', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, help_text="Indique si c'est une catégorie principale"),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
    ]
