# Generated by Django 5.0.2 on 2025-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_clean_duplicate_categories'),
        ('product', '0010_remove_phonevariant_image_phonevariantimage'),
    ]

    operations = [
    ]
