# Generated by Django 5.2a1 on 2025-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_add_samsung_phones'),
        ('product', '0010_remove_phonevariant_image_phonevariantimage'),
    ]

    operations = [
    ]
