# Generated by Django 5.1.4 on 2025-05-25 07:26

import saga.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la catégorie', null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to='categories/%Y/%m/%d/'),
        ),
    ]
