# Generated by Django 5.2a1 on 2025-04-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_clean_duplicate_categories'),
        ('product', '0011_merge_20250418_2212'),
    ]

    operations = [
    ]
