# Generated by Django 5.1.4 on 2025-05-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_fix_duplicate_created_at'),
        ('product', '0012_add_product_fields_correctly'),
        ('product', 'add_product_fields'),
    ]

    operations = [
    ]
