# Generated by Django 5.1.4 on 2025-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Neuf'), ('used', 'Occasion'), ('refurbished', 'Reconditionné')], max_length=20, null=True, verbose_name='État du produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_warranty',
            field=models.BooleanField(default=False, verbose_name='Garantie'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='Produit tendance'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de ventes'),
        ),
    ]
