# Generated by Django 5.1.4 on 2025-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_condition_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_methods',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.shippingmethod', verbose_name='Méthodes de livraison'),
        ),
    ]
