# Generated by Django 5.1.4 on 2025-05-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_add_default_shipping_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='warranty',
        ),
    ]
