# Generated by Django 5.2a1 on 2025-02-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_category_options_remove_product_content_type_and_more'),
        ('suppliers', '0002_remove_supplier_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier'),
        ),
    ]
