# Generated by Django 5.1.4 on 2025-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_phone_warranty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalitem',
            options={'verbose_name': 'Livre et Culture', 'verbose_name_plural': 'Livres et Culture'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
