# Generated by Django 4.2.10 on 2025-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='bazin_quality',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='fabric_quality',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='length',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='width',
        ),
        migrations.AddField(
            model_name='clothing',
            name='material',
            field=models.CharField(blank=True, help_text='Matériau du vêtement (coton, polyester, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='season',
            field=models.CharField(blank=True, help_text="Saison d'utilisation", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='style',
            field=models.CharField(blank=True, help_text='Style du vêtement (casual, formel, sport, etc.)', max_length=100, null=True),
        ),
    ]
