# Generated by Django 4.2.10 on 2025-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_clothing_bazin_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salam_delivery_days',
            field=models.PositiveIntegerField(default=14, help_text='Délai estimé pour les produits en vente Salam', verbose_name='Délai de livraison Salam (jours)'),
        ),
        migrations.AddField(
            model_name='product',
            name='salam_stock',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'unités disponibles en commande Salam", verbose_name='Stock Salam disponible'),
        ),
    ]
