# Generated by Django 4.2.10 on 2025-06-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_salam_delivery_days_product_salam_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='salam_stock',
        ),
    ]
