# Generated by Django 4.2.10 on 2025-06-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_salam_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='salam_delivery_days',
        ),
    ]
