# Generated by Django 4.2.10 on 2025-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_salam_delivery_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='resolution',
            field=models.CharField(default='1920x1080', help_text="Résolution de l'écran (ex: 1920x1080)", max_length=50),
        ),
    ]
