# Generated by Django 4.2.10 on 2026-01-07 18:39

from django.db import migrations, models
import product.models
import saga.storage_backends
import saga.utils.security


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_add_external_fields_to_historicalproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_available', '-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la catégorie', null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to='categories/%Y/%m/%d/', validators=[saga.utils.security.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='image',
            field=models.TextField(blank=True, help_text='Image de la catégorie', max_length=100, null=True, validators=[saga.utils.security.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[saga.utils.security.validate_image_file], verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to=product.models.get_product_gallery_image_upload_path, validators=[saga.utils.security.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=saga.storage_backends.ProductImageStorage(), upload_to=product.models.get_product_main_image_upload_path, validators=[saga.utils.security.validate_image_file], verbose_name='Image principale'),
        ),
    ]
