# Generated by Django 4.2.10 on 2026-01-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_options_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(blank=True, help_text='Niveau dans la hiérarchie B2B (0, 1, 2, 3...)', null=True, verbose_name='Niveau hiérarchique (B2B)'),
        ),
        migrations.AddField(
            model_name='category',
            name='rayon_type',
            field=models.CharField(blank=True, help_text="Type de rayon depuis l'API B2B (ex: frais_libre_service, epicerie)", max_length=100, null=True, verbose_name='Type de rayon (B2B)'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='level',
            field=models.IntegerField(blank=True, help_text='Niveau dans la hiérarchie B2B (0, 1, 2, 3...)', null=True, verbose_name='Niveau hiérarchique (B2B)'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='rayon_type',
            field=models.CharField(blank=True, help_text="Type de rayon depuis l'API B2B (ex: frais_libre_service, epicerie)", max_length=100, null=True, verbose_name='Type de rayon (B2B)'),
        ),
    ]
