# Generated by Django 4.2.10 on 2026-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL externe de l'image (B2B)", max_length=500, null=True),
        ),
    ]
