# Generated by Django 4.2.10 on 2025-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BoliBana Sugu', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone sans indicatif', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('rccm', models.CharField(blank=True, help_text='Numéro RCCM', max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('company_name', models.CharField(default='BoliBana Sugu', max_length=100)),
                ('company_type', models.CharField(default='Entreprise individuelle', max_length=50)),
                ('company_address', models.CharField(default='Bamako, Mali', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche')),
                ('meta_keywords', models.TextField(blank=True, help_text='Mots-clés pour les moteurs de recherche')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Activer le mode maintenance')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('opening_hours', models.TextField(blank=True, help_text="Horaires d'ouverture (ex: Lun-Ven: 8h-18h)")),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
