# Generated by Django 4.2.10 on 2025-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='delivery_info',
            field=models.TextField(blank=True, help_text='Informations sur la livraison'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL du favicon'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL du logo du site'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ninea_number',
            field=models.CharField(blank=True, help_text='Numéro NINEA', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='opening_hours_detailed',
            field=models.TextField(blank=True, help_text='Horaires détaillés pour le footer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='return_policy',
            field=models.TextField(blank=True, help_text='Politique de retour'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp (sans indicatif)', max_length=20),
        ),
    ]
