# Generated by Django 4.2.10 on 2025-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_delivery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_story_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Notre histoire'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_story_title',
            field=models.CharField(default='Notre histoire', help_text="Titre du lien 'Notre histoire'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_values_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Nos valeurs'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_values_title',
            field=models.CharField(default='Nos valeurs', help_text="Titre du lien 'Nos valeurs'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_center_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Centre d'aide'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_center_title',
            field=models.CharField(default="Centre d'aide", help_text="Titre du lien 'Centre d'aide'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_returns_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Retours faciles'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_returns_title',
            field=models.CharField(default='Retours faciles', help_text="Titre du lien 'Retours faciles'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_warranty_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Garantie qualité'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='help_warranty_title',
            field=models.CharField(default='Garantie qualité', help_text="Titre du lien 'Garantie qualité'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_express_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Livraison express'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_express_title',
            field=models.CharField(default='Livraison express', help_text="Titre du lien 'Livraison express'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_loyalty_content',
            field=models.TextField(blank=True, help_text="Contenu de la page 'Fidélité Boli'"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_loyalty_title',
            field=models.CharField(default='Fidélité Boli', help_text="Titre du lien 'Fidélité Boli'", max_length=100),
        ),
    ]
