# Generated by Django 4.2.10 on 2025-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_siteconfiguration_service_loyalty_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='ID du Facebook Pixel (Meta Pixel)', max_length=50),
        ),
    ]
