# Generated by Django 4.2.10 on 2025-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_facebook_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_access_token',
            field=models.CharField(blank=True, help_text="Token d'accès Facebook pour l'API Conversions", max_length=500),
        ),
    ]
