# Generated by Django 4.2.10 on 2026-03-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifiant unique (ex: cgv, about, help-center)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Titre de la page', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Contenu HTML de la page')),
                ('is_published', models.BooleanField(default=True, help_text="Page visible via l'API")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page statique',
                'verbose_name_plural': 'Pages statiques',
                'ordering': ['title'],
            },
        ),
    ]
