# Generated by Django 5.1.4 on 2025-05-29 23:42

import django.core.validators
import saga.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.TextField(verbose_name='Sous-titre')),
                ('background_image', models.ImageField(storage=saga.storage_backends.HeroImageStorage(), upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name="Image d'arrière-plan")),
                ('primary_button_text', models.CharField(max_length=50, verbose_name='Texte du bouton principal')),
                ('primary_button_url', models.CharField(max_length=200, verbose_name='URL du bouton principal')),
                ('secondary_button_text', models.CharField(max_length=50, verbose_name='Texte du bouton secondaire')),
                ('secondary_button_url', models.CharField(max_length=200, verbose_name='URL du bouton secondaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heros',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
