# Generated by Django 5.2a1 on 2025-02-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product_count',
        ),
    ]
