# Generated by Django 5.2a1 on 2025-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplier_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
