# Generated by Django 5.1.4 on 2025-05-30 00:00

import django.core.validators
import django.db.models.deletion
import saga.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='background_image',
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=saga.storage_backends.HeroImageStorage(), upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suppliers.hero')),
            ],
            options={
                'verbose_name': 'Image du hero',
                'verbose_name_plural': 'Images du hero',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
