# Generated by Django 5.1.4 on 2025-05-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_update_supplier_fields'),
        ('suppliers', '0002_update_supplier_timestamps'),
    ]

    operations = [
    ]
