# Generated by Django 5.2a1 on 2025-04-12 06:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ML'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='specialty',
            field=models.CharField(choices=[('Fournisseur de TELEPHONE', 'Fournisseur de TELEPHONE'), ('Fournisseur de TELEVISION', 'Fournisseur de TELEVISION')], max_length=100),
        ),
    ]
