# Generated by Django 5.1.4 on 2025-05-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_update_supplier_data'),
        ('suppliers', '0003_update_timestamps'),
        ('suppliers', '0004_alter_supplier_options_alter_supplier_company_name_and_more'),
    ]

    operations = [
    ]
