# Generated by Django 5.0.2 on 2025-04-20 13:05

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=240, unique=True, verbose_name='Adresse email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='ex: +223 76 00 00 00', max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('fidelys_number', models.CharField(blank=True, max_length=240, null=True, unique=True, verbose_name='Numéro Fidelys')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='ex: mahi watara', max_length=100, null=True, verbose_name='Nom complet')),
                ('address_type', models.CharField(blank=True, choices=[('DOM', 'Domicile'), ('BUR', 'Bureau'), ('AUT', 'Autre')], default='DOM', help_text='ex: Domicile, Bureau, Autre', max_length=3, null=True, verbose_name="Type d'adresse")),
                ('quarter', models.CharField(help_text='ex: Hamdallaye ACI 2000', max_length=100, verbose_name='Quartier')),
                ('street_address', models.CharField(help_text='ex: Rue 123, porte 456', max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(choices=[('BKO', 'Bamako'), ('KAY', 'Kayes'), ('KOU', 'Koulikoro'), ('SIK', 'Sikasso'), ('SEG', 'Ségou'), ('MOP', 'Mopti'), ('TOM', 'Tombouctou'), ('GAO', 'Gao'), ('KID', 'Kidal'), ('MEN', 'Ménaka'), ('TAO', 'Taoudénit')], default='BKO', max_length=3, verbose_name='Ville')),
                ('additional_info', models.CharField(blank=True, help_text='ex: Bâtiment, étage, etc.', max_length=255, null=True, verbose_name='Informations complémentaires')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('uidb64', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
