# Generated by Django 5.1.4 on 2025-05-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopper_phone_number_shopper_address_and_more'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='shopper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
