# Generated by Django 5.2a1 on 2025-02-09 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopper_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('DOM', 'Domicile'), ('BUR', 'Bureau'), ('AUT', 'Autre')], default='DOMICILE', max_length=3, verbose_name="Type d'adresse")),
                ('quarter', models.CharField(help_text='ex: Hamdallaye ACI 2000', max_length=100, verbose_name='Quartier')),
                ('street_address', models.CharField(help_text='ex: Rue 123, porte 456', max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(choices=[('BKO', 'Bamako'), ('KAY', 'Kayes'), ('KOU', 'Koulikoro'), ('SIK', 'Sikasso'), ('SEG', 'Ségou'), ('MOP', 'Mopti'), ('TOM', 'Tombouctou'), ('GAO', 'Gao'), ('KID', 'Kidal'), ('MEN', 'Ménaka'), ('TAO', 'Taoudénit')], default='BKO', max_length=3, verbose_name='Ville')),
                ('additional_info', models.TextField(blank=True, help_text='ex: Bâtiment, étage, etc.', null=True, verbose_name='Informations complémentaires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
    ]
