# Generated by Django 5.2a1 on 2025-02-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(blank=True, help_text='ex: mahi watara', max_length=100, null=True, verbose_name='Nom complet'),
        ),
    ]
