# Generated by Django 5.2a1 on 2025-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shippingaddress_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Adresse par défaut'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('DOM', 'Domicile'), ('BUR', 'Bureau'), ('AUT', 'Autre')], default='DOM', max_length=3, verbose_name="Type d'adresse"),
        ),
    ]
