# Generated by Django 5.1.4 on 2025-05-24 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_allowedip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedip',
            options={'ordering': ['-created_at'], 'verbose_name': 'IP autorisée', 'verbose_name_plural': 'IPs autorisées'},
        ),
        migrations.RemoveField(
            model_name='allowedip',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='allowedip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shopper',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
