# Generated by Django 5.2a1 on 2025-02-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shippingaddress_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='additional_info',
            field=models.CharField(blank=True, help_text='ex: Bâtiment, étage, etc.', max_length=255, null=True, verbose_name='Informations complémentaires'),
        ),
    ]
