# Generated by Django 5.1.4 on 2025-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_allowedip_options_remove_allowedip_last_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='is_verified',
        ),
    ]
