# Generated by Django 5.2a1 on 2025-02-15 19:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_shippingaddress_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(max_length=240, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='fidelys_number',
            field=models.CharField(blank=True, max_length=240, null=True, unique=True, verbose_name='Numéro Fidelys'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='ex: +223 76 00 00 00', max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
