# Generated by Django 4.2.10 on 2026-02-01 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalshopper'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('loyalty_level', models.CharField(choices=[('Bronze', 'Bronze'), ('Argent', 'Argent'), ('Or', 'Or'), ('Diamant', 'Diamant')], max_length=20)),
                ('total_spent', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique fidélité',
                'verbose_name_plural': 'Historique fidélité',
                'ordering': ['-created_at'],
            },
        ),
    ]
