# Generated by Django 5.2a1 on 2025-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_shopper_date_of_birth_alter_shopper_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
