# Generated by Django 4.2.29 on 2026-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loyaltyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshopper',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications push activées'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications push activées'),
        ),
    ]
