# Generated by Django 5.2a1 on 2025-02-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_twofactorcode_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='uidb64',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
