# Generated by Django 5.2a1 on 2025-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_twofactorcode_uidb64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('DOM', 'Domicile'), ('BUR', 'Bureau'), ('AUT', 'Autre')], default='DOM', help_text='ex: Domicile, Bureau, Autre', max_length=3, null=True, verbose_name="Type d'adresse"),
        ),
    ]
